version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: mern-backend-dev
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -lc "npm install && npm run dev"

  frontend:
    build:
      context: ./frontend
    container_name: mern-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -lc "bun install && bun run dev --host 0.0.0.0"
